-- Check actual table structure in ANALYTICS schema
USE ECOMMERCE_DB.ANALYTICS;

-- Check what tables exist
SELECT 'EXISTING TABLES:' as INFO;
SHOW TABLES IN SCHEMA ANALYTICS;

-- Check STG_EVENTS_CART structure
SELECT 'STG_EVENTS_CART COLUMNS:' as INFO;
DESCRIBE TABLE STG_EVENTS_CART;

-- Check STG_EVENTS_PURCHASE structure  
SELECT 'STG_EVENTS_PURCHASE COLUMNS:' as INFO;
DESCRIBE TABLE STG_EVENTS_PURCHASE;

-- Check STG_EVENTS_VIEW structure
SELECT 'STG_EVENTS_VIEW COLUMNS:' as INFO;
DESCRIBE TABLE STG_EVENTS_VIEW;

-- Check CUSTOMER_360_PROFILE structure
SELECT 'CUSTOMER_360_PROFILE COLUMNS:' as INFO;
DESCRIBE TABLE CUSTOMER_360_PROFILE;

-- Check sample data from each table
SELECT 'SAMPLE DATA FROM STG_EVENTS_CART:' as INFO;
SELECT * FROM STG_EVENTS_CART LIMIT 3;

SELECT 'SAMPLE DATA FROM STG_EVENTS_PURCHASE:' as INFO;
SELECT * FROM STG_EVENTS_PURCHASE LIMIT 3;

SELECT 'SAMPLE DATA FROM STG_EVENTS_VIEW:' as INFO;
SELECT * FROM STG_EVENTS_VIEW LIMIT 3;

SELECT 'SAMPLE DATA FROM CUSTOMER_360_PROFILE:' as INFO;
SELECT * FROM CUSTOMER_360_PROFILE LIMIT 3; 